name: map_flutter
description: A new Flutter project.

publish_to: "none" 


version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"


dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_map: ^3.1.0
  geolocator: ^9.0.2
  latlong2: ^0.8.1
  haversine: ^1.0.2
  

dev_dependencies:

  
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  
  uses-material-design: true
 